# Generated by Django 2.2.1 on 2019-05-23 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotherEntity',
            fields=[
                ('CreatedDateTime', models.DateTimeField(auto_created=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('LastModifiedDateTime', models.DateTimeField(auto_now=True)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.EntityType')),
            ],
        ),
    ]
