# Generated by Django 2.2.1 on 2019-05-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherentity',
            name='CreatedDateTime',
        ),
    ]
